const esStore = [{
  img: 'JavaScript函数式编程.jpg',
  key: 'js',
  name: 'JavaScript函数式编程',
  url: 'https://pan.baidu.com/s/1BiXyr6kC-5_rpAtAxZUcRw'
}, {
  img: 'CSS世界.jpg',
  key: 'js',
  name: 'CSS世界',
  url: 'https://pan.baidu.com/s/1f0SHJbxNdCr4P38NT7Pbzg'
}, {
  img: 'JavaScript设计模式与开发实践.jpg',
  key: 'js',
  name: 'JavaScript设计模式与开发实践',
  url: 'https://pan.baidu.com/s/1Q2dzzOJNQuU-BnW3PeyfNw'
}, {
  img: 'exploring-es6.jpg',
  key: 'js',
  name: 'exploring-es6',
  url: 'https://pan.baidu.com/s/1R6ciel95bOMRBkYNtqpyXQ'
}, {
  img: 'JavaScript高级程序设计.jpg',
  key: 'js',
  name: 'JavaScript高级程序设计(第3版)',
  url: 'https://pan.baidu.com/s/1zzixTA07vsRgSsgGOyYImg'
}, {
  img: 'HTML5 CANVAS基础教程.jpg',
  key: 'js',
  name: 'HTML5 CANVAS基础教程',
  url: 'https://pan.baidu.com/s/1YEcBzxDT03pUOgolawftug'
}, {
  img: '深入浅出Node.js.jpg',
  key: 'js',
  name: '深入浅出Node.js',
  url: 'https://pan.baidu.com/s/1B48LF_qD4gmPvhDI6waVrQ'
}, {
  img: 'WebKit技术内幕.jpg',
  key: 'js',
  name: 'WebKit技术内幕',
  url: 'https://pan.baidu.com/s/1iBwll4Yq1mvPFPAQbou6aw'
}, {
  img: '你不知道的JavaScript.jpg',
  key: 'js',
  name: '你不知道的JavaScript',
  url: 'https://pan.baidu.com/s/1nnynw7Rsl_l4Wv9LhZjXFg'
}, {
  img: 'node与express开发.jpg',
  key: 'js',
  name: 'node与express开发',
  url: 'https://pan.baidu.com/s/17svB0MzzFK1rjlsARuhndA'
}, {
  img: 'Node.js实战.jpg',
  key: 'js',
  name: 'Node.js实战 中文版',
  url: 'https://pan.baidu.com/s/1eIa3PD2Ec4adtCIrv2NN9A'
}, {
  img: 'Javascript性能优化：度量、监控与可视化.jpg',
  key: 'js',
  name: 'Javascript性能优化：度量、监控与可视化',
  url: 'https://pan.baidu.com/s/1NWhfaZ4jvrCUGHFHLVaSyQ'
}, {
  img: 'Javascript高效图形编程.jpg',
  key: 'js',
  name: 'Javascript高效图形编程',
  url: 'https://pan.baidu.com/s/1l167pV7N12TlVHfuPeiIZQ'
}, {
  img: 'JavaScript基础与案例开发详解.jpg',
  key: 'js',
  name: 'JavaScript基础与案例开发详解',
  url: 'https://pan.baidu.com/s/1_SlufbnY7mG9TdQ62rLxnA'
}, {
  img: 'Node即学即用.jpg',
  key: 'js',
  name: 'Node即学即用',
  url: 'https://pan.baidu.com/s/17resHUReYge5SS-1KPqing'
}, {
  img: 'HTML5游戏开发.jpg',
  key: 'js',
  name: 'HTML5游戏开发',
  url: 'https://pan.baidu.com/s/1r29le4g3s57Zox0N09eGTA'
}, {
  img: 'Bootstrap实战.jpg',
  key: 'js',
  name: 'Bootstrap实战',
  url: 'https://pan.baidu.com/s/1c7uSQOIWqSA0kDULuLMHXQ'
}, {
  img: 'Ajax安全技术.jpg',
  key: 'js',
  name: 'Ajax安全技术',
  url: 'https://pan.baidu.com/s/1KOjxb1C3ENl29UyA7EqG2g'
}, {
  img: 'JavaScript王者归来.jpg',
  key: 'js',
  name: 'JavaScript王者归来',
  url: 'https://pan.baidu.com/s/1slBgU9OpUyLehlQ70WqVow'
}, {
  img: 'HTML5 Canvas 游戏开发实战.jpg',
  key: 'js',
  name: 'HTML5 Canvas 游戏开发实战',
  url: 'https://pan.baidu.com/s/10DfwhChJDr1_HYlZ5NiICg'
}, {
  img: 'CSS权威指南.jpg',
  key: 'js',
  name: 'CSS权威指南',
  url: 'https://pan.baidu.com/s/171x3nHtfDhAldlJMVCPoew'
}, {
  img: 'JavaScript语言精粹.jpg',
  key: 'js',
  name: 'JavaScript语言精粹',
  url: 'https://pan.baidu.com/s/1axp9K-VrQ1rhIgQ8Yr2HKA'
}, {
  img: '全端Web开发：使用JavaScript与Java.jpg',
  key: 'js',
  name: '全端Web开发：使用JavaScript与Java',
  url: 'https://pan.baidu.com/s/1hfsffeHYJm1B7dQlZtME7Q'
}, {
  img: 'jQuery应用开发实践指南.jpg',
  key: 'js',
  name: 'jQuery应用开发实践指南',
  url: 'https://pan.baidu.com/s/1qjeVUYdVySlEblpmR6M3GQ'
}, {
  img: 'CSS那些事.jpg',
  key: 'js',
  name: 'CSS那些事儿',
  url: 'https://pan.baidu.com/s/1JW6A9QrF-dj0YOKi3aotiw'
}, {
  img: 'AngularJS权威教程.jpg',
  key: 'js',
  name: 'AngularJS权威教程',
  url: 'https://pan.baidu.com/s/1eotVEAk7dhA3Yel6ibu0NA'
}, {
  img: 'ExtJS权威指南.jpg',
  key: 'js',
  name: 'ExtJS权威指南',
  url: 'https://pan.baidu.com/s/108WytrNnhT9jaZcsbftQaw'
}, {
  img: 'ExtJS 开发实战.jpg',
  key: 'js',
  name: 'ExtJS 开发实战',
  url: 'https://pan.baidu.com/s/1A6ybHVES7cXMZhT6eyBpqA'
}, {
  img: 'jQuery技术内幕.jpg',
  key: 'js',
  name: 'jQuery技术内幕 深入解析jQuery架构设计与实现原理',
  url: 'https://pan.baidu.com/s/1GzBI0hG9HW7gNeRH3cu22w'
}]

export default esStore
